# Site settings
title: A guide to designing and understanding centralized daycare admissions
author:
  name: John Kennes
  email: johnkennes@gmail.com
description: "Site about daycare admission systems."

# Build settings
remote_theme: jekyll/minima
